{
  try {
    super.run();
  }
 catch (  Exception e) {
    System.out.println("ex found in run");
    engine.newMessage=true;
    e.printStackTrace(engine.leechErr);
  }
}
